### ISSUE TITLE
refreshdata crashes due to removal of INSPQ CSV files

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#28]
In September the INSPQ CSV files were removed which now results in a `404` when requesting these resources.

`refreshdata` successfully downloads the sources but then crashes when processing the INSPQ files:

```
Traceback (most recent call last):
  ...
  File "../covid19mtl/app/refreshdata.py", line 552, in <module>
    sys.exit(main())
  File "../covid19mtl/app/refreshdata.py", line 533, in main
    update_data_qc_csv(sources_dir, processed_dir)
  File "../covid19mtl/app/refreshdata.py", line 371, in update_data_qc_csv
    qc_df = pd.read_csv(lastest_source_file, encoding='utf-8')
  File "../covid19mtl/.venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "../covid19mtl/.venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "../covid19mtl/.venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "../covid19mtl/.venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 929, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 916, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2071, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 25, saw 2
```

There seems to be a bug in `refreshdata.fetch` (https://github.com/jeremymoreau/covid19mtl/blob/4adb5b43d5167239ed94996ce3691e394bb8cfba/app/refreshdata.py#L139-L140) that causes the `404` page to be fetched and saved.

I think an error fetching one resource should not affect downloading other resources. Maybe just log it?

**Comment by merwok** [comment]
Right!  Probably that line of code needs to be `continue`, to go into the next iteration, rather than `next` which references a function and does nothing with it :slightly_smiling_face:

**Comment by mschoettle** [comment]
That's it. However, it will then cause a crash during the sources download. The other sources are downloaded still because they are before the INSPQ ones in the list of sources.

Might be fine to keep it that way but alternatively it could continue for those that work with these two changes:
* report (log) when a source cannot be downloaded after multiple attempts
* when processing the new data, skip the files that don't exist
